apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169442916
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169442916
    app.kubernetes.io/part-of: test-app-169442916
  name: go-169442916
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169442916
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169442916
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads-stage/skhileri-tenant/test-app-169442916/go-169442916@sha256:c3fbcd3131a2c72ed69f40ffe6775d41ce5bd29d86a3fe08756f6dfafb437a89
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
